name: CI

on: [push, pull_request]

env:
  DATABASE_URL: ${{secrets.DATABASE_URL}}

jobs:
  build:
    name: 👷 - Build application

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/checkout@v3
      - name: 🧰 - Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: 📦 - Install dependencies
        run: pnpm install

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Print Environment Variable
        run: echo $MY_ENV_VAR
